### ISSUE TITLE
php-fpm sometimes becomes a zombie with boot2docker and nfs

### ISSUE THREAD

**Issue by Sebobo** [Sebobo/Shel.DockerFlow#11]
On Mac with boot2docker with vagrant and nfs, sometimes php-fpm doesn't do
anything anymore and the only way I know how to get it running again is to completely 
force restart the box.
This should be fixed. Maybe it's a bug in the php config or just a boot2docker problem with nfs.

**Comment by Sebobo** [comment]
This could be related to my Vagrantfile mounting the same folder twice, will do further research.

**Comment by visay** [comment]
Hi @Sebobo,

Any update on this issue?

Cheers,
Visay

**Comment by Sebobo** [comment]
No, we can close it for now until I experience it again
