### ISSUE TITLE
Add standardize changelog

### ISSUE THREAD

**Issue by visay** [Sebobo/Shel.DockerFlow#12]
Hi @Sebobo,

Please see 2b5947c72922e122d30f07c47bd28ed906cb6c9b, it is a suggestion of the formatted changelog with symantic versioning. I'm not sure whether we should add date and author in the log and/or we should remove the prefix type like [TASK] out of the log.

The generate log was adjusted to be easily understandable by user reading it, thus some commit messages were removed / modified.

I don't do the pull request here because I want to rebase it once we agree together and after a proper tag has been created.

Cheers,
Visay

**Comment by Sebobo** [comment]
Cool. I think we should just have a similar style to the other TYPO3 changelogs. See:
http://docs.typo3.org/neos/TYPO3NeosDocumentation/1.2/Appendixes/ChangeLogs/122.html

That would be:

    [prefix] commit short

    commit description

Don't think we need the commit hash. We could add the author. Sometimes people who do merge requests really like to be named ;)

**Comment by visay** [comment]
Hi @Sebobo ,

- I agree with having `[PREFIX] Commit short (Author Name)`
- I don't think commit description is needed because that will make our changelog file grow big unneccessary fast.
- In Neos, the changelog is automatically generated by jenkins in ReST format and they have one file for each release. That is something we don't need yet, imo.
- I would prefer a quick overview of release change in the log similar to gitlab changelog https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CHANGELOG. So as a user, I can quickly decide if i want to upgrade or not. In case I'm interested in details of a change, I can find out in github commit view or `git log`.

Because I wanted to merge your pull request related to docker-composer (https://github.com/Sebobo/Shel.DockerFlow/pull/15), I need to first have a tag of the current version so that dockerhub can build an image with the old version so I can use it in my existing development projects. Therefore, I pushed the changelog with tag 0.0.1 and point the build image to this version.

So for 0.0.1, the changelog is as my original suggestion but feel free to adjust the format.
