### ISSUE TITLE
Ngnix config for resources should work for both Flow 2.3 or 3.0

### ISSUE THREAD

**Issue by visay** [Sebobo/Shel.DockerFlow#21]
With the following commit, it is not possible anymore for dockerflow master branch to run Flow 2.3

    [!!!BUGFIX] Fix Ngnix config for resources to work with Neos 2.0

We need to find a way to make both Flow 2.3 and 3.0 to work with dockerflow master by either configure dynamic nginx config for resource (preferred if possible) or by detecting Flow version and then deliver the right config based on that.

**Comment by Sebobo** [comment]
Just saw this on Slack:  

    location ~ "^/_Resources/Persistent/" {
        access_log off;
        try_files  $uri @neos12AndBefore;
    }

    # Backward compatibility: these are rewrite rules needed for Neos 1.2 and before 
    location @neos12AndBefore {
        rewrite "(.{40})/.+\.(.+)"                        /_Resources/Persistent/$1.$2 break;
        rewrite "([a-z0-9]+/(.+/)?[a-f0-9]{40})/.+\.(.+)" /_Resources/Persistent/$1.$2 break;
    }

We could adapt and try that

**Comment by visay** [comment]
Fixed with 555f4f0e730b90034f9a7cc546a6b965c9ecdcc3
