### ISSUE TITLE
[FEATURE] To be able to send mail out from the app container

### ISSUE THREAD

**Issue by visay** [Sebobo/Shel.DockerFlow#5]
We need the app server to be able to send out email so that we can test the form. I tweak the dockerfile to install ssmtp and it works great but I don't like its approach because I have to configure an smtp user.

We need to configure sendmail or something alike so that php mail functionality work out of the built container.

**Comment by Sebobo** [comment]
Yes you are right.
Maybe we can do it similar to like they did here https://registry.hub.docker.com/u/sysdia/docker-php-server/dockerfile/

**Comment by Sebobo** [comment]
@visay I have updated the dockerfile to install sendmail.
Also the app image will now be built at https://registry.hub.docker.com/u/sebobo/shel.dockerflow after every commit to the master.
This way we can use it's verified built and the developers don't need to build it locally.

**Comment by visay** [comment]
- Mail functionality works like a charm for me. Thanks for taking care :-)
- I cannot use your build image from docker hub because of user ID for mount drive is different and I will have to look into this soon. Currently I still use my own local build.
