### ISSUE TITLE
Discussion: Support for TYPO3 CMS

### ISSUE THREAD

**Issue by visay** [Sebobo/Shel.DockerFlow#6]
Hi @Sebobo,

Having used this dockerflow for sometimes, I really like its speed and easiness to start a Neos/Flow project. I want to start a discussion whether we should make this package more generic that will support TYPO3 CMS or should we have a separate package like "DockerCMS" or doesn't need to do it at all.

What do you think?

Cheers,
Visay

**Comment by Sebobo** [comment]
Makes sense. Maybe we can combine it 
So what would we need to support CMS?

* Different Document root
* Any Libraries?
* Different vhost config for nginx?
* Where do we get the sources from?

**Comment by Sebobo** [comment]
More information about settings up CMS with composer: http://composer.typo3.org/
